version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./saves:/home/app/saves
      - ./.env:/home/app/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
